[package]
name = "reason-solver"
version = "0.1.0"
authors = ["Aidan Swope <aidanswope@gmail.com>"]
edition = "2018"

[dependencies]
reason-othello = { path = "../reason-othello"}
arrayvec = "0.5.2"

[dev-dependencies]
indicatif = "0.15.0"